### ISSUE TITLE
JSON errors when using gem

### ISSUE THREAD

**Issue by jjeffers** [CopperEgg/copperegg-ruby#4]
```
/.../gems/ruby-1.8.7-p371/gems/json-1.7.7/lib/json/pure/generator.rb:336:in `to_json': wrong argument type JSON::Pure::Generator::State (expected Data) (TypeError)
    from /Users/jjeffers/.rvm/gems/ruby-1.8.7-p371/gems/json-1.7.7/lib/json/pure/generator.rb:336:in `json_transform'
    from /Users/jjeffers/.rvm/gems/ruby-1.8.7-p371/gems/json-1.7.7/lib/json/pure/generator.rb:329:in `each'
    from /Users/jjeffers/.rvm/gems/ruby-1.8.7-p371/gems/json-1.7.7/lib/json/pure/generator.rb:329:in `json_transform'
    from /Users/jjeffers/.rvm/gems/ruby-1.8.7-p371/gems/json-1.7.7/lib/json/pure/generator.rb:311:in `to_json'
    from /Users/jjeffers/.rvm/gems/ruby-1.8.7-p371/gems/json-1.7.7/lib/json/pure/generator.rb:336:in `json_transform'
    from /Users/jjeffers/.rvm/gems/ruby-1.8.7-p371/gems/json-1.7.7/lib/json/pure/generator.rb:329:in `each'
    from /Users/jjeffers/.rvm/gems/ruby-1.8.7-p371/gems/json-1.7.7/lib/json/pure/generator.rb:329:in `json_transform'
    from /Users/jjeffers/.rvm/gems/ruby-1.8.7-p371/gems/json-1.7.7/lib/json/pure/generator.rb:311:in `to_json'
    from /Users/jjeffers/.rvm/gems/ruby-1.8.7-p371/gems/json-1.7.7/lib/json/pure/generator.rb:265:in `generate'
    from /Users/jjeffers/.rvm/gems/ruby-1.8.7-p371/gems/json-1.7.7/lib/json/common.rb:223:in `generate'
    from /Users/jjeffers/.rvm/gems/ruby-1.8.7-p371/gems/copperegg-0.6.1/lib/copperegg/mixins/persistence.rb:47:in `request'
    from /Users/jjeffers/.rvm/gems/ruby-1.8.7-p371/gems/copperegg-0.6.1/lib/copperegg/metric_sample.rb:8:in `save'
```

copperegg (0.6.1)
json (1.7.7, 1.7.6, 1.6.1)
json_pure (1.7.7)

ruby version 1.8.7-352

```
CopperEgg::MetricSample.save("server_calls", "my_identifier", Time.now.to_i, {:last_20_calls => successes})
```

**Comment by jznadams** [comment]
Was this ever resolved? I get the exact same error after copying and pasting the example code from the "Edit Metric Group" page of Uptime Cloud Monitor. I'm using Ruby 2.1.5, copperegg v0.6.1, json_pure v1.7.7

`CopperEgg::MetricSample.save("delayed_jobs", "my_delayed_jobs_identifier", Time.now.to_i, {:workers => 723, :jobs => 4853})`

 The syntax in the readme seems different than the example code, but I get the same results with either approach.
